### ISSUE TITLE
Chat 기능 구현

### ISSUE THREAD

**Issue by eastfilmm** [KNUChat/KNUChat#31]
- [ ] chat 기본 기능 구현
- [ ] css 적용

**Comment by krokerdile** [comment]
오른쪽 사이드바에 라벨, 프로젝트, 브랜치 걸어뒀음~ 다른 거 만들때도 걸어서 해주라

**Comment by eastfilmm** [comment]
해당 내용 처리해놨음

**Comment by eastfilmm** [comment]
Chat 기능 구현 issue-#31 close
